mysql:
    image: mysql:5.7.11
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=password
    ports:
        - "13306:3306"
    # volumes:
    #     - mysql-data:/var/lib/mysql
apache-php:
    image: php:5.6.19-apache
    ports:
        - "81:80"
    volumes:
        - ./src:/var/www/html
    links:
        - mysql:db
phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    ports:
        - "8080:8080"
    links:
        - mysql:db
